### ISSUE TITLE
Use an environment variable to override auto_reload

### ISSUE THREAD

**Issue by href** [morepath/more.chameleon#1]
Pyramid's chameleon integration has `PYRAMID_RELOAD_TEMPLATES`, an environment variable which one can use to override the auto_reload setting.

Would this make sense here as `MORE_CHAMELEON_RELOAD_TEMPLATES` or `MOREPATH_RELOAD_TEMPLATES`?

**Comment by webmaven** [comment]
`MOREPATH_RELOAD_TEMPLATES` seems better to me, no need for separate env vars for each templating implementation.

**Comment by faassen** [comment]
I agree with @webmaven on the name of the environment variable.

How would we implement this? Is overriding the way the chameleon settings are initialized with code that inspects the temporary variable enough? The drawback of this is that if you implement your own settings section to override the default one, you lose the ability to set the environment variable.

If the environment variable should be respected no matter what, then it makes more sense to override it when we copy the settings section in `get_template_loader`.

We should also change this behavior in the Jinja2 implementation, I think.

**Comment by href** [comment]
Both approaches seem less then ideal for me. I really can't say which one I prefer :confused:

**Comment by faassen** [comment]
Well, you should go into the reasons why both are less than ideal so we can weigh them. I think the second approach of overriding it with the env variable in get_template_loader is a reasonable approach myself, but you seem to disagree.

**Comment by webmaven** [comment]
@faassen :+1:

**Comment by href** [comment]
I totally missed your reply here @faassen, sorry!

The first approach has the drawback of being overwritten by accident. But it's really great in it's simplicity. It's a setting, so putting it into settings is very obvious.

The second approach can't be accidentally overwritten, which is great, but I don't like that we can't use settings for things like this. It's like 'settings' should really be named 'constants'. Settings seems like something that can change during runtime.

But that is surely outside the scope of this ticket. I'm really okay with both approaches. Adding `MOREPATH_RELOAD_TEMPLATES` is what counts.

**Comment by faassen** [comment]
I think I prefer the second approach, as it makes sense you want this to always work, no matter what you've done with template rendering settings otherwise.

I don't think the fact that settings cannot be changed during runtime is related to why settings shouldn't be used for this override. An environment variable is known ahead of time and settings can access it just fine. The problem is that the settings are also used to override _other_ behavior for template rendering and that if you do so, the environment variable is completely ignored. 

I think we have two parallel kinds of override here:
- override by application subclass.
- override by environment variables.

It's almost as if the environment variable-based settings should be in an application that is at the bottom of the application inheritance chain. Or to see it differently, we should be able to say: this piece of configuration cannot be overridden by subclasses. Something like that.

But for the time being I think we should ignore the settings system for this and use the environment variable directly in both template engines.

**Comment by href** [comment]
:+1:

**Comment by href** [comment]
If you want I can add this change using the second approach. This is what I would do:
- Remove the settings for more.chameleon altogether, as we have no other settings.
- Remove the mention of the settings in the readme.
- Write a new part for the readme, describing the environment variable.
- Add the environment variable to the template loader.

**Comment by faassen** [comment]
I don't want to remove the settings altogether. We still want to support other settings people may want to configure. See https://chameleon.readthedocs.org/en/latest/library.html#chameleon.PageTemplate for a list of things. Plus we use the special sauce prepend search path setting too (but that is hardcoded).

We do need to modify the README to describe the environment variable (`MOREPATH_TEMPLATE_AUTO_RELOAD`, I think)

We also should update more.jinja2 to support the same environment variable. If you don't want to do this work at least place an issue in its issue tracker so we don't forget what to do, pointing to this issue.

**Comment by faassen** [comment]
Oh, and please do go ahead if you're okay with this!

**Comment by href** [comment]
I missed to other settings, thanks. Sure, I'm fine with doing it, at least for more.chameleon for a start.

**Comment by faassen** [comment]
Looks good. I did leave a question about one line of code in the github.
